### ISSUE TITLE
Not working with latest versions

### ISSUE THREAD

**Issue by kdawgwilk** [hubot-archive/hubot-ambush#4]
Trying to use with latest versions and got this on the server

```
[Thu May 14 2015 13:40:31 GMT-0600 (MDT)] ERROR TypeError: Cannot read property '<user_name>' of undefined
  at appendAmbush (/Sources/busy/qa/busybot/node_modules/hubot-ambush/src/ambush.coffee:17:14, <js>:6:9)
  at TextListener.callback (/Sources/busy/qa/busybot/node_modules/hubot-ambush/src/ambush.coffee:29:7, <js>:21:9)
  at TextListener.Listener.call (/Sources/busy/qa/busybot/node_modules/hubot/src/listener.coffee:27:7, <js>:23:14)
  at Robot.receive (/Sources/busy/qa/busybot/node_modules/hubot/src/robot.coffee:197:9, <js>:143:33)
  at SlackBot.Adapter.receive (/Sources/busy/qa/busybot/node_modules/hubot/src/adapter.coffee:66:5, <js>:47:25)
  at SlackBot.message (/Sources/busy/qa/busybot/node_modules/hubot-slack/src/slack.coffee:154:20, <js>:189:21)
  at Client.<anonymous> (/Sources/busy/qa/busybot/node_modules/hubot-slack/src/slack.coffee:1:1, <js>:3:61)
  at Client.emit (events.js:107:17)
  at Client.onMessage (/Sources/busy/qa/busybot/node_modules/hubot-slack/node_modules/slack-client/src/client.js:477:14)
  at WebSocket.<anonymous> (/Sources/busy/qa/busybot/node_modules/hubot-slack/node_modules/slack-client/src/client.js:140:24)
  at WebSocket.emit (events.js:110:17)
  at Receiver.self._receiver.ontext (/Sources/busy/qa/busybot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/WebSocket.js:697:10)
  at Receiver.opcodes.1.finish (/Sources/busy/qa/busybot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/Receiver.js:397:14)
  at Receiver.expectHandler (/Sources/busy/qa/busybot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/Receiver.js:384:31)
  at Receiver.add (/Sources/busy/qa/busybot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/Receiver.js:93:24)
  at TLSSocket.firstHandler (/Sources/busy/qa/busybot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/WebSocket.js:678:22)
  at TLSSocket.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:163:16)
  at TLSSocket.Readable.push (_stream_readable.js:126:10)
  at TCP.onread (net.js:529:20)
```

**Comment by kdawgwilk** [comment]
Seems this problem has to do with the using the hubot-slack adapter
